// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GitAdd(arg1:string,arg2:string):Promise<string>;

export function GitBlame(arg1:string,arg2:string):Promise<Array<models.GitBlameLine>>;

export function GitBranch(arg1:string):Promise<string>;

export function GitBranchLog(arg1:string,arg2:string,arg3:number):Promise<string>;

export function GitCheckout(arg1:string,arg2:string):Promise<string>;

export function GitClone(arg1:string,arg2:string):Promise<string>;

export function GitCommit(arg1:string,arg2:string):Promise<string>;

export function GitCommitAmend(arg1:string,arg2:string):Promise<string>;

export function GitCreateBranch(arg1:string,arg2:string):Promise<string>;

export function GitDiffFiles(arg1:string):Promise<string>;

export function GitFetch(arg1:string):Promise<string>;

export function GitFileDiff(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function GitGetCurrentBranch(arg1:string):Promise<string>;

export function GitGetGraphHistory(arg1:string,arg2:number):Promise<string>;

export function GitGetMergeConflicts(arg1:string):Promise<Array<string>>;

export function GitGetRemoteInfo(arg1:string):Promise<Array<models.GitRemoteInfo>>;

export function GitGetStagedFiles(arg1:string):Promise<Array<models.GitFileStatus>>;

export function GitGetStatusStructured(arg1:string):Promise<Array<models.GitFileStatus>>;

export function GitInit(arg1:string):Promise<string>;

export function GitLocalBranches(arg1:string):Promise<string>;

export function GitLog(arg1:string,arg2:number):Promise<string>;

export function GitMerge(arg1:string,arg2:string):Promise<string>;

export function GitPull(arg1:string,arg2:string):Promise<string>;

export function GitPush(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function GitRebase(arg1:string,arg2:string):Promise<string>;

export function GitRemoteBranches(arg1:string):Promise<string>;

export function GitResetFile(arg1:string,arg2:string):Promise<string>;

export function GitResolveConflict(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GitShowBranchTree(arg1:string):Promise<string>;

export function GitStageAll(arg1:string):Promise<string>;

export function GitStageFile(arg1:string,arg2:string):Promise<string>;

export function GitStashApply(arg1:string,arg2:string):Promise<string>;

export function GitStashDrop(arg1:string,arg2:string):Promise<string>;

export function GitStashList(arg1:string):Promise<Array<models.GitStash>>;

export function GitStashPop(arg1:string,arg2:string):Promise<string>;

export function GitStashSave(arg1:string,arg2:string):Promise<string>;

export function GitStatus(arg1:string):Promise<string>;

export function GitUnstageFile(arg1:string,arg2:string):Promise<string>;

export function Greet():Promise<string>;

export function OpenInBrowser(arg1:string):Promise<void>;
