// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GitBranch(arg1) {
  return window['go']['main']['App']['GitBranch'](arg1);
}

export function GitInit(arg1) {
  return window['go']['main']['App']['GitInit'](arg1);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function Greet() {
  return window['go']['main']['App']['Greet']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}
