// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GitInit(arg1:string):Promise<string>;

export function GitStatus(arg1:string):Promise<string>;

export function Greet():Promise<string>;

export function OpenInBrowser(arg1:string):Promise<void>;
