// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerInfo() {
  return window['go']['main']['App']['GetServerInfo']();
}

export function GitAdd(arg1, arg2) {
  return window['go']['main']['App']['GitAdd'](arg1, arg2);
}

export function GitBranch(arg1) {
  return window['go']['main']['App']['GitBranch'](arg1);
}

export function GitCheckout(arg1, arg2) {
  return window['go']['main']['App']['GitCheckout'](arg1, arg2);
}

export function GitClone(arg1, arg2) {
  return window['go']['main']['App']['GitClone'](arg1, arg2);
}

export function GitCommit(arg1, arg2) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2);
}

export function GitCreateBranch(arg1, arg2) {
  return window['go']['main']['App']['GitCreateBranch'](arg1, arg2);
}

export function GitGetCurrentBranch(arg1) {
  return window['go']['main']['App']['GitGetCurrentBranch'](arg1);
}

export function GitInit(arg1) {
  return window['go']['main']['App']['GitInit'](arg1);
}

export function GitLog(arg1, arg2) {
  return window['go']['main']['App']['GitLog'](arg1, arg2);
}

export function GitShowBranchTree(arg1) {
  return window['go']['main']['App']['GitShowBranchTree'](arg1);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function Greet() {
  return window['go']['main']['App']['Greet']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function StartHTTPServer(arg1) {
  return window['go']['main']['App']['StartHTTPServer'](arg1);
}

export function StopHTTPServer() {
  return window['go']['main']['App']['StopHTTPServer']();
}
