// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerInfo():Promise<Record<string, any>>;

export function GitAdd(arg1:string,arg2:string):Promise<string>;

export function GitBranch(arg1:string):Promise<string>;

export function GitCheckout(arg1:string,arg2:string):Promise<string>;

export function GitClone(arg1:string,arg2:string):Promise<string>;

export function GitCommit(arg1:string,arg2:string):Promise<string>;

export function GitCreateBranch(arg1:string,arg2:string):Promise<string>;

export function GitGetCurrentBranch(arg1:string):Promise<string>;

export function GitInit(arg1:string):Promise<string>;

export function GitLog(arg1:string,arg2:number):Promise<string>;

export function GitShowBranchTree(arg1:string):Promise<string>;

export function GitStatus(arg1:string):Promise<string>;

export function Greet():Promise<string>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function StartHTTPServer(arg1:number):Promise<string>;

export function StopHTTPServer():Promise<string>;
