// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GitAdd(arg1, arg2) {
  return window['go']['main']['App']['GitAdd'](arg1, arg2);
}

export function GitBlame(arg1, arg2) {
  return window['go']['main']['App']['GitBlame'](arg1, arg2);
}

export function GitBranch(arg1) {
  return window['go']['main']['App']['GitBranch'](arg1);
}

export function GitBranchLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitBranchLog'](arg1, arg2, arg3);
}

export function GitCheckout(arg1, arg2) {
  return window['go']['main']['App']['GitCheckout'](arg1, arg2);
}

export function GitClone(arg1, arg2) {
  return window['go']['main']['App']['GitClone'](arg1, arg2);
}

export function GitCommit(arg1, arg2) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2);
}

export function GitCommitAmend(arg1, arg2) {
  return window['go']['main']['App']['GitCommitAmend'](arg1, arg2);
}

export function GitCreateBranch(arg1, arg2) {
  return window['go']['main']['App']['GitCreateBranch'](arg1, arg2);
}

export function GitDiffFiles(arg1) {
  return window['go']['main']['App']['GitDiffFiles'](arg1);
}

export function GitFetch(arg1) {
  return window['go']['main']['App']['GitFetch'](arg1);
}

export function GitFileDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitFileDiff'](arg1, arg2, arg3);
}

export function GitGetCurrentBranch(arg1) {
  return window['go']['main']['App']['GitGetCurrentBranch'](arg1);
}

export function GitGetGraphHistory(arg1, arg2) {
  return window['go']['main']['App']['GitGetGraphHistory'](arg1, arg2);
}

export function GitGetMergeConflicts(arg1) {
  return window['go']['main']['App']['GitGetMergeConflicts'](arg1);
}

export function GitGetRemoteInfo(arg1) {
  return window['go']['main']['App']['GitGetRemoteInfo'](arg1);
}

export function GitGetStagedFiles(arg1) {
  return window['go']['main']['App']['GitGetStagedFiles'](arg1);
}

export function GitGetStatusStructured(arg1) {
  return window['go']['main']['App']['GitGetStatusStructured'](arg1);
}

export function GitInit(arg1) {
  return window['go']['main']['App']['GitInit'](arg1);
}

export function GitLocalBranches(arg1) {
  return window['go']['main']['App']['GitLocalBranches'](arg1);
}

export function GitLog(arg1, arg2) {
  return window['go']['main']['App']['GitLog'](arg1, arg2);
}

export function GitMerge(arg1, arg2) {
  return window['go']['main']['App']['GitMerge'](arg1, arg2);
}

export function GitPull(arg1, arg2) {
  return window['go']['main']['App']['GitPull'](arg1, arg2);
}

export function GitPush(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitPush'](arg1, arg2, arg3);
}

export function GitRebase(arg1, arg2) {
  return window['go']['main']['App']['GitRebase'](arg1, arg2);
}

export function GitRemoteBranches(arg1) {
  return window['go']['main']['App']['GitRemoteBranches'](arg1);
}

export function GitResetFile(arg1, arg2) {
  return window['go']['main']['App']['GitResetFile'](arg1, arg2);
}

export function GitResolveConflict(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitResolveConflict'](arg1, arg2, arg3);
}

export function GitShowBranchTree(arg1) {
  return window['go']['main']['App']['GitShowBranchTree'](arg1);
}

export function GitStageAll(arg1) {
  return window['go']['main']['App']['GitStageAll'](arg1);
}

export function GitStageFile(arg1, arg2) {
  return window['go']['main']['App']['GitStageFile'](arg1, arg2);
}

export function GitStashApply(arg1, arg2) {
  return window['go']['main']['App']['GitStashApply'](arg1, arg2);
}

export function GitStashDrop(arg1, arg2) {
  return window['go']['main']['App']['GitStashDrop'](arg1, arg2);
}

export function GitStashList(arg1) {
  return window['go']['main']['App']['GitStashList'](arg1);
}

export function GitStashPop(arg1, arg2) {
  return window['go']['main']['App']['GitStashPop'](arg1, arg2);
}

export function GitStashSave(arg1, arg2) {
  return window['go']['main']['App']['GitStashSave'](arg1, arg2);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function GitUnstageFile(arg1, arg2) {
  return window['go']['main']['App']['GitUnstageFile'](arg1, arg2);
}

export function Greet() {
  return window['go']['main']['App']['Greet']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}
